paths:
  data_base_dir: "./data"
  user_data_dir: "./data/user"
  accounts_list: "./src/accounts.json"
  categories_file: "./src/categories.json"

google_drive:
  folder_id: "1N0LSvAdD1kHZJ4XaCSo8O93v6NX9JljO"
  scopes:
    - "https://www.googleapis.com/auth/drive.file"

defaults:
  categories:
    - Food
    - Salary
    - Transport
    - Entertainment
    - Others
